### ISSUE TITLE
Docker + SQLite deploy error

### ISSUE THREAD

**Issue by helloxz** [casbin/casibase#969]
I am planning to use SQLite as the database, here is my app.conf

```
driverName = sqlite
dataSourceName = "file:/db/casibase.db?cache=shared"
dbName = casibase
```

`docker-compose.yaml` content is:

```
version: '3'

services:
 casbin:
   container_name: casibase
   image: casbin/casibase:latest
   restart: always
   volumes:
     - ./config/app.conf:/conf/app.conf
     - ./db/casibase.db:/db/casibase.db
   ports:
     - "14000:14000"
```

Error occurred after startup:

```
goroutine 1 [running]:
github.com/casibase/casibase/object.(*Adapter).createTable(0xc0002732c0)
        /go/src/casibase/object/adapter.go:160 +0x3a5
github.com/casibase/casibase/object.CreateTables()
        /go/src/casibase/object/adapter.go:78 +0x3a
main.main()
        /go/src/casibase/main.go:32 +0x3e
panic: SQL logic error: out of memory (1)

goroutine 1 [running]:
github.com/casibase/casibase/object.(*Adapter).createTable(0xc0002ed540)
        /go/src/casibase/object/adapter.go:160 +0x3a5
github.com/casibase/casibase/object.CreateTables()
        /go/src/casibase/object/adapter.go:78 +0x3a
main.main()
        /go/src/casibase/main.go:32 +0x3e
panic: SQL logic error: out of memory (1)

goroutine 1 [running]:
github.com/casibase/casibase/object.(*Adapter).createTable(0xc00028a5c0)
        /go/src/casibase/object/adapter.go:160 +0x3a5
github.com/casibase/casibase/object.CreateTables()
        /go/src/casibase/object/adapter.go:78 +0x3a
main.main()
        /go/src/casibase/main.go:32 +0x3e
```
